Traceback (most recent call last):
  File "C:\Users\alejo\Projects\Consultoria\manage.py", line 22, in <module>
    main()
  File "C:\Users\alejo\Projects\Consultoria\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\commands\makemigrations.py", line 213, in handle
    loader.project_state(),
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\migrations\loader.py", line 361, in project_state
    return self.graph.make_state(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\migrations\graph.py", line 329, in make_state
    project_state = self.nodes[node].mutate_state(project_state, preserve=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\migrations\migration.py", line 91, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\migrations\operations\fields.py", line 169, in state_forwards
    state.remove_field(app_label, self.model_name_lower, self.name)
  File "C:\Users\alejo\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\migrations\state.py", line 258, in remove_field
    old_field = model_state.fields.pop(name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'nombre'
